a = 1 # a is a integer
b = 3.5 # b is float
c = "govind" # c is string
d = True # d is boolean
d = False # d is boolean
e = [1, 2, 3, 4] # e is list
f = (1, 2, 3, 4) # f is tuple
g = {1, 2, 3, 4} # g is set
h = {"name": "govind", "age": 25} # h is dictionary
i = None # i is NoneType
j = 2 + 3j # j is complex number
k = b"govind" # k is bytes
l = bytearray(b"govind") # l is bytearray   
m = memoryview(b"govind") # m is memoryview
n = frozenset([1, 2, 3, 4]) # n is frozenset
o = range(10) # o is range
p = lambda x: x + 1 # p is function
q = type(a) # q is type
r = isinstance(a, int) # r is boolean
s = issubclass(bool, int) # s is boolean
t = globals() # t is dictionary
u = locals() # u is dictionary
v = dir() # v is list   
w = id(a) # w is integer
x = hash(a) # x is integer
y = repr(a) # y is string
z = str(a) # z is stri